### PR TITLE
docs: Set up docs directory like other repos

### LINKED ISSUE #19: FASM readthedocs is broken

### PR DESCRIPTION
**Pull request by daniellimws**
- Add Makefile and conf.py to test documentation locally
- Add environment.yml and requirements.txt to set up conda through `make env`
- Include specification.rst in index.rst so that it shows up in readthedocs

Close #19

Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

### CODE REVIEW

**Comment by mithro** [comment]
Look like this is causing travis to fail?
```
py34 run-test-pre: PYTHONHASHSEED='1816414488'
py34 run-test: commands[0] | check-manifest --ignore 'tox.ini,tests*'
lists of files in version control and sdist do not match!
missing from sdist:
  docs/Makefile
  docs/_static
  docs/_static/.keepme
  docs/conf.py
  docs/environment.yml
  docs/requirements.txt
suggested MANIFEST.in rules:
  recursive-include docs *.keepme
  recursive-include docs *.py
  recursive-include docs *.txt
  recursive-include docs *.yml
  recursive-include docs Makefile
ERROR: InvocationError for command /home/travis/build/SymbiFlow/fasm/.tox/py34/bin/check-manifest --ignore 'tox.ini,tests*' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py34: commands failed
The command "tox" exited with 1.
```

**Comment by daniellimws** [comment]
Fixed travis

**Comment by mithro** [comment]
@daniellimws - This seems to cause readthedocs to fail? https://github.com/SymbiFlow/fasm/commit/0b5723cc8b5fe8c263e84652e67b17cdf186bf97

**Comment by daniellimws** [comment]
It seems that virtualenv is used to generate the docs https://readthedocs.org/projects/fasm/builds/10920233/

**Comment by mithro** [comment]
Seems like you missed the [`.readthedocs.yml`](https://github.com/SymbiFlow/python-symbiflow-v2x/blob/master/.readthedocs.yml) -- I added it in https://github.com/SymbiFlow/fasm/pull/24

**Comment by mithro** [comment]
Seems like this is failing now with;
```
Running Sphinx v2.4.4
fatal: --unshallow on a complete repository does not make sense
make: Circular links <- links dependency dropped.
```

**Pull request merged**
